---
title: "Assignment 1"
author: "*Ebru Gecici*"
date: "04/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Short Story of My life**

My name is Ebru Geçici and I am an *Industrial Engineer*. I graduated from the Yıldız Technical University and now I am the Master student at Boğaziçi University. At the same time, I work in the Yıldız Technical University as an academic researcher. 

In my academic journey, I especially study optimization problems such as *shift scheduling*, *exam and course scheduling problem*, and also *energy modeling* with mathematical modeling. In addition to these studies, I started to interest the data project. For this purpose, I got some online courses about R Programming. I hope that this course will be an important milestone in my studies.   

Computer Skills:

- R Programming
- Python 
- MS Office 

To get detailed information about my studies, you can visit my web-pages:

[**Google Scholar**](https://scholar.google.com/citations?hl=tr&user=t_fx7jwAAAAJ)  
[**Linkedin**](https://tr.linkedin.com/in/ebrugecici)

# **Some News About *R* **
## useR! 2020 Toulouse
### Multi-stage Financial Modeling using Machine Learning in R

In the R Conference, which is accessed on YouTube, one of the project participants provides information about multi-stage financial modeling in R. The package focuses on commodity prices such as corn, cotton, and soybean, which are affected by many factors like weather, economy, etc.  Moreover, these data can be obtained via different sources and they can be from time horizon, e.g. daily, monthly, and weekly. To read, merge, clean, and visualize this data financial modeling package can be used. The video provides a simple implementation of the financial modeling package by using soybean prices. Moreover, it provides an example of a model which is obtained by using R programming. This model is transformed into a dashboard, which is a kind of decision support system. This system provides visualization and trial for financial modeling.

Detailed information can be obtained from the [YouTube]( https://www.youtube.com/watch?v=-cgwDHzd0p4)

## An R View into Epidemiology 
Today, the most important issue in health care is Covid-19, which is a pandemic with high infectivity around the world. Even though many people take into account the prevention to protect themselves, these protections are not enough to disappear from the virus. For this reason, people check the daily data news about the pandemic and they estimate the future of the spread of this virus. The blog, which is written by *Joseph Rickert*, mentions that the comparison of the model about pandemic can be difficult, i.e., especially you are not an expert in this area.  For this reason, in this post, the author provides useful materials for people, who are R literate or interested in the R programming language. In other words, there are packages, which can be useful to make an analysis about the epidemic.

The essay, *An R view into Epidemiology*, provides information about packages about epidemics. According to the results, there are nearly a hundred packages that take place in the R. Note that these packages information can be obtained by using **pkgserach** and **dlstat** functions, which give information about packages and download information about the packages, respectively. Six of epidemic packages are **DSAIDE**, **epicontacts**,  **EpiEstim**, **EpiModel**, **epitrix**, **surveillance**. This post provides information about these packages. Most of these packages can be used by experts,on the other hand, the documentation of these packages is understandable to both experts, students, and people who are interested in epidemics and R.

For more information, you can visit the [blog page](https://rviews.rstudio.com/2020/05/20/some-r-resources-for-epidemiology/)

## Analyzing Data from Covid19 R Package
Another Covid19 related study, which is obtained by using R programming, is posted by R-bloggers. In this post, the Covid19 R package is introduced and some implementation with this package is presented. The used data is collected from the Human Mortality Database. To make analyzing **covid19** function is used. This function contains more information, for this reason, to make an analysis some parts of this information, i.e., country, date, population, and death parameters, are used. After this filtering process, the data is visualized by using **ggplot** function. Then to find the most affected countries, the query was addressed in the post.

To see the detail of the R implementation, you can visit [blog page]( https://www.r-bloggers.com/analyzing-data-from-covid19-r-package/)


## Covid Epidemiology with R
Another Covid and R programming related post is presented by *Tim Churches*. In the R CRAN, there are some packages related to the epidemics. By using these packages, data can be rearranged, and by using this data some predictions and calculations can be made. In this post, US Covid data from Johns Hopkins University and Wikipedia (by using *rvest* package, i.e., part of *tidyverse*) is rearranged. By using **earlyR** and **EpiEstim** packages, these data are analyzed. That is, **get_R()** function is used to calculate the maximum likelihood estimate for reproduction number, and **overall_infectivity()** function in EpiEstim calculates the infectivity of the pandemic. These values also can be visualized by using ggplot2 function. However, this calculation is only one part of the study. For this process, the incidence package is used to fit the log-linear model. By using this package, two models can be created: the growth phase and the decay phase. In the current situation, the pandemic is in the growth phase, for this reason in the post only growth phase model is presented. Then, by using this model, the future of the pandemic can be estimated. 

In shorts, the Covid data can be visualized, analyzed, modeled, and estimated by using R packages and functions. By using these packages, useful decision tools can be created to give information about Covid19. 

To get more information about the R implementation in Covid19, you can visit [blog page](https://rviews.rstudio.com/2020/03/05/covid-19-epidemiology-with-r/)




###### *Assignment 1 presented by EG*
